variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- build
- test
- clean
  
build:
  stage: build
  script:
  - ./gradlew clean
  - mkdir -p src/fraction/cpp
  - "echo \"#include \\\"fraction.hpp\\\"\nfraction test {0};\" > src/fraction/cpp/fraction.cpp"
  - ./gradlew assemble
  when: on_success

test:
  stage: test
  script:
  - ./gradlew clean
  - ./gradlew check
  when: on_success
  artifacts:
    reports:
      junit: build/test-results/*/*/gtestresults.xml

clean:
  stage: clean
  script:
  - ./gradlew clean
  when: always
